[build]
  command = "bash build.sh"
  publish = "release/wwwroot"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
# local dev command directory
  port = 8888

  # Local dev command. A.k.a npm start
  #command = "dotnet watch run --project ./src/mts.web/mts.web.csproj"
